### PR TITLE
Ft user registration page 162977957

### PR DESCRIPTION
**Pull request by teekize**
## What does this PR do?
This PR adds the user registration page

## Description of task to be completed
1. create a registration form

## How to manually test this
1. Git clone this repository
2. Cd into the working directory
3. Branch off to this branch 
4. open the registration form on any web browser of your choice

## Screenshot
sign up

### CODE REVIEW

**Comment by luqee** [comment]
Nice work on your UI, but I think making the inputs a little wider would help with user experience.

**Comment by Ogollah** [comment]
It's also too dark in here.

**Comment by teekize** [comment]
Thank you let me implement this feedback

**Comment by CaptainMumo** [comment]
It looks quite okay to me. Keep up.

**Pull request merged**
